spring.application.name=UserService

server.port=8050

spring.datasource.url=jdbc:mysql://localhost:3306/ecomuserms?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mandatory to add the below properties if you are using port number for eureka except 8761
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# The below property useful in cloud deployment only
eureka.instance.prefer-ip-address=true

logging.pattern.level='%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]'
